---
plugin: community.general.proxmox
url: "{{ proxmox_url }}"
validate_certs: false

user: "{{ proxmox_user }}"
token_id: "{{ proxmox_token_id }}"
token_secret: "{{ proxmox_token_secret }}"

want_facts: true
want_proxmox_nodes_ansible_host: true

filters:
  - proxmox_status == "running"

keyed_groups:
  # Group by each individual tag
  - key: proxmox_tags_parsed | list
    prefix: tag
    separator: '_'